name: Deploy Frontend App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Update dependencies
      - name: Update dependencies
        run: npm update

      # Step 5: Build the React app
      - name: Build React app
        run: npm run build

      # Step 6: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 7: Deploy to S3
      - name: Deploy to S3
        run: |
          # Remove existing files from S3 bucket
          aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }} --recursive

          # Upload the build files to S3 bucket
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }}
