name: Deploy Application

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Sync Frontend Directory
        run: |
          sudo rsync -av --delete /home/ubuntu/actions-runner-frontend/_work/Trilokpropco-frontend/Trilokpropco-frontend/ /home/ubuntu/Trilokpropco-frontend/

      - name: Build and Deploy Frontend
        run: |
          cd /home/ubuntu/Trilokpropco-frontend 
          rm -rf node_modules
          npm install
          npm run build
          sudo cp -r ./dist/* /var/www/html  # Make sure the frontend build outputs to 'dist'

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
